version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongod:/data/db

  backend:
    build: ./backend  
    container_name: backend
    restart: always
    ports:
      - "8400:8400"
    environment:
      - MONGO_DB_URI=mongodb://mongodb:27017/music 
    depends_on:
      - mongodb
   
volumes:
  mongod:

